# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfb3072bea7a78a2a6b150d4be71e541611631d7f76ed5e74cd5b170a512f19f73b8064ec3a36be6066185648a2914faf44dc65da6504f5d7558fc648694bea8

test:
  secret_key_base: cadd78ac0a3d580eb56c6c081f6ac2afdbc0fd3ee374595ba4ca9b24c803a53eb8a6b6240af299f47ff34a22f06f4811928b51b6fda9d448a962bab34ab777db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
